name: Dragonhide Belt
automation:
- type: counter
  counter: Dragonhide Belt
  amount: '1'
  allowOverflow: false
  errorBehaviour: warn
  fixedValue: true
- type: roll
  dice: 1d{4+2*((caster.levels.get('Monk')+1)//6)}
  name: recoveredKi
  hidden: false
  displayName: Ki Recovered
- type: text
  text: 'This finely detailed belt is made of dragonhide. While wearing it, you gain
    a bonus to the saving throw DCs of your ki features.


    In addition, you can use an action to regain ki points equal to a roll of your
    Martial Arts die. You can''t use this action again until the next dawn.'
  title: Effect
- type: counter
  counter: Ki Points
  amount: -recoveredKi
  allowOverflow: true
  errorBehaviour: warn
  fixedValue: false
_v: 2
proper: true
verb: tightens their
activation_type: 1
list_display_override: Recover 1d{4+2*((MonkLevel+1)//6)} Ki Points until the next dawn.
