_v: 2
name: Greatsword of Life Stealing
automation:
  - type: target
    target: all
    effects:
      - type: variable
        name: not_construct_or_undead
        value: not target.creature_type or not ('construct' in
          target.creature_type.lower() or 'undead' in
          target.creature_type.lower() )
        onError: "0"
      - type: attack
        hit:
          - type: damage
            damage: 2d6 +{strengthMod} [slashing] {{"+10 [necrotic] " if
              not_construct_or_undead and lastAttackNaturalRoll == 20 else ""}}
            overheal: false
        miss: []
        attackBonus: strengthMod +proficiencyBonus
  - type: condition
    condition: lastAttackNaturalRoll == 20
    onTrue:
      - type: target
        target: self
        effects:
          - type: temphp
            amount: ({caster.temp_hp} [current thp], 10)kh1
    onFalse: []
    errorBehaviour: "false"
  - type: text
    text: When you attack a creature with this magic weapon and roll a 20 on the
      attack roll, that target takes an extra 10 necrotic damage if it isn't a
      construct or an undead. You also gain 10 temporary hit points.
    title: Effect
thumb: https://www.dndbeyond.com/avatars/thumbnails/18/911/315/315/636381757412406581.jpeg
