name: Javelin of Lightning (2024)
automation:
  - type: variable
    name: useCharge
    value: choice and choice in 'lightning bolt'
    onError: "0"
  - type: condition
    condition: useCharge
    onTrue:
      - type: counter
        counter: Javelin of Lightning
        amount: "1"
        errorBehaviour: raise
      - type: roll
        dice: 4d6 [magical lightning]
        name: damage
      - type: target
        target: all
        effects:
          - type: save
            stat: dex
            fail:
              - type: damage
                damage: "{damage}"
            success:
              - type: damage
                damage: "{damage}/2"
            dc: "13"
    onFalse:
      - type: target
        target: all
        effects:
          - type: attack
            hit:
              - type: damage
                damage: 1d6 + {strengthMod} [magical lightning]
            miss: []
            attackBonus: strengthMod + proficiencyBonus
    errorBehaviour: "true"
  - type: text
    text: >-
      Each time you make an attack roll with this magic weapon and hit, you can
      have it deal Lightning damage instead of Piercing damage.


      _Use `-choice bolt` to turn the javelin into a lightning bolt._
    title: Description
  - type: text
    text: When you throw this weapon at a target no farther than 120 feet from you,
      you can forgo making a ranged attack roll and instead turn the weapon into
      a bolt of lightning. This bolt forms a 5-foot-wide Line between you and
      the target. The target and each other creature in the Line (excluding you)
      makes a DC 13 Dexterity saving throw, taking 4d6 Lightning damage on a
      failed save or half as much damage on a successful one. Immediately after
      dealing this damage, the weapon reappears in your hand. This property
      can't be used again until the next dawn.
    title: Lightning Bolt
_v: 2
proper: false
