name: Pyroconverger  # !cc create "Pyroconverger Uses" -min 0 -max 10 -reset long -resetto 0 #
automation:
  - type: counter
    counter: Pyroconverger Uses
    amount: "-1"
    allowOverflow: true
    errorBehaviour: warn
    fixedValue: true
  - type: variable
    name: uses
    value: lastCounterRemaining
  - type: roll
    dice: 1d10
    name: Malfunction
    hidden: true
    fixedValue: true
  - type: condition
    condition: "{{lastCounterRemaining<10}}"
    onTrue:
      - type: roll
        dice: 4d6[fire]
        name: damage
        hidden: false
      - type: target
        target: all
        effects:
          - type: save
            stat: dex
            fail:
              - type: damage
                damage: "{damage}"
                overheal: false
            success:
              - type: damage
                damage: ({damage})/2
                overheal: false
            dc: "13"
      - type: condition
        condition: (int(Malfunction)+lastCounterRemaining) >= 11
        onTrue:
          - type: counter
            counter: Pyroconverger Uses
            amount: "-10"
            allowOverflow: true
            errorBehaviour: warn
            fixedValue: true
          - type: target
            target: self
            effects:
              - type: damage
                damage: 4d6 [fire]
                overheal: false
                fixedValue: true
          - type: text
            text: >-
              Malfunction Roll: 1d10 ({{f'**{Malfunction}**' if Malfunction==10 or
              Malfunction==1 else Malfunction}}) + {uses} [uses] =
              `{{int(Malfunction)+uses}}`


              Your Pyroconverger malfunctions and explodes in your hands!


              As an action, you can cause the Pyroconverger to project fire in a 10-foot cone. Each creature in that area must make a DC 13 Dexterity saving throw, taking 4d6 fire damage on a failed save, or half as much damage on a successful one.


              Each time you use the Pyroconverger, roll a d10 and add the number of times you have used it since your last long rest. If the total is 11 or higher, the Pyroconverger malfunctions: you take 4d6 fire damage, and you can't use the Pyroconverger again until you finish a long rest.
            title: Effect
        onFalse:
          - type: text
            text: >-
              Malfunction Roll: 1d10 ({{f'**{Malfunction}**' if Malfunction==10 or
              Malfunction==1 else Malfunction}}) + {uses} [uses] =
              `{{int(Malfunction)+uses}}`


              As an action, you can cause the Pyroconverger to project fire in a 10-foot cone. Each creature in that area must make a DC 13 Dexterity saving throw, taking 4d6 fire damage on a failed save, or half as much damage on a successful one.


              Each time you use the Pyroconverger, roll a d10 and add the number of times you have used it since your last long rest. If the total is 11 or higher, the Pyroconverger malfunctions: you take 4d6 fire damage, and you can't use the Pyroconverger again until you finish a long rest.
            title: Effect
        errorBehaviour: raise
    onFalse:
      - type: text
        text: >-
          Your pyroconverger is in an advanced state of disrepair. It should be all
          better after a long rest.


          Each time you use the Pyroconverger, roll a d10 and add the number of times you have used it since your last long rest. If the total is 11 or higher, the Pyroconverger malfunctions: you take 4d6 fire damage, and you can't use the Pyroconverger again until you finish a long rest.
        title: Effect
    errorBehaviour: "false"
_v: 2
verb: shoots a cone of fire with
thumb: https://media.discordapp.net/attachments/759950160980607008/977290904123625512/kill-it-with-fire-fire.gif
activation_type: 3
list_display_override: 'Makes an attack with Izzet''s second best flamethrower (because Niv is the first): The Pyroconverger!  You do need a counter named "Pyroconverger Uses"'
