_v: 2
name: Vorpal Blade
automation:
  - type: target
    target: each
    effects:
      - type: variable
        name: isResistant
        value: target.resistances.is_resistant('magical slashing')
        onError: "0"
      - type: attack
        hit:
          - type: variable
            name: nat20
            value: lastAttackNaturalRoll==20
            onError: "0"
          - type: damage
            damage: 1d8 + {3+strengthMod}{{'+3d8' if nat20 else ''}} [magical slashing{{'^' if
              isResistant else ''}}]
        miss: []
        attackBonus: 3+strengthMod+proficiencyBonus
  - type: text
    text: >-
      You gain a +3 bonus to attack and damage rolls made with this magic
      weapon. In addition, the weapon ignores resistance to slashing damage.


      When you attack a creature that has at least one head with this weapon and roll a 20 on the attack roll, you cut off one of the creature's heads. The creature dies if it can't survive without the lost head. A creature is immune to this effect if it is immune to slashing damage, doesn't have or need a head, has legendary actions, or the GM decides that the creature is too big for its head to be cut off with this weapon. Such a creature instead takes an extra 6d8 slashing damage from the hit.
    title: Effect
verb: strikes with the
proper: true
thumb: https://media-waterdeep.cursecdn.com/avatars/thumbnails/19/264/315/315/636382375131575300.jpeg
list_display_override: The Vorpal Blade will sever the head of the target on a natural 20.  This attack will apply the extra 6d8 on a 20, allowing the GM to decide if the head is removed.
